### ISSUE TITLE
Trailing dash in repo name?

### ISSUE THREAD

**Issue by szabgab** [robrwo/Plack-Middleware-Greylist-#2]
There is a trailing dash in the repo name. It looks strange. Is that intentional?

**Comment by robrwo** [comment]
That was a typo when I created the repo. I've only just noticed.

Is that causing problems for any tools?

**Comment by szabgab** [comment]
I don't think so, it just surprised me.

**Comment by szabgab** [comment]
But you can easily rename it on the GitHub UI

**Comment by robrwo** [comment]
Yes. But then I'll need to update distribution metadata, and that might break things.

**Comment by szabgab** [comment]
I doubt that it will break anything and GitHub installs a redirect....

**Comment by robrwo** [comment]
Some of the metadata didn't have the dash. Possibly github was ignoring it. Anyhow, fixed in next release. Thanks.

**Comment by szabgab** [comment]
Excellent. Thanks. I'll try to send a PR adding GitHub Actions for CI.
