### ISSUE TITLE
Doesn't seem to work with ipv6 addresses

### ISSUE THREAD

**Issue by accursedm0** [robrwo/Plack-Middleware-Greylist-#6]
When handling ipv6 address this line 

`$self->_match( sub { return $match->match_ip(@_) } );`

is throwing a warning

`inet_aton: failed at...`

**Comment by robrwo** [comment]
It uses [Net::IP::Match::Trie](https://metacpan.org/pod/Net::IP::Match::Trie) which I suspect does not support IPv6.

**Comment by robrwo** [comment]
I could try using [Net::IP::LPM](https://metacpan.org/pod/Net::IP::LPM) as an alternative.

**Comment by accursedm0** [comment]
Thank you! That does look promising indeed :+1:

**Comment by robrwo** [comment]
Please try this https://metacpan.org/release/RRWO/Plack-Middleware-Greylist-v0.5.3-TRIAL

**Comment by robrwo** [comment]
Let me know if this and https://metacpan.org/release/RRWO/Plack-Middleware-Greylist-v0.5.4-TRIAL fix your issues here and #7

**Comment by accursedm0** [comment]
Yes, this seems to fix the issue. Thank you very much!
